@startuml
|Download process|
start
:launch a job;

:**step1**;
|#AntiqueWhite|job execution|
:load the book;
:parse the subpage count;
:calculate the pic count;
:insert pictures metadata into db;
|Download process|

:**step2**;
|job execution|
:retrieve a list of 10 picture from db;
:add to download thread pool;
:download the pictures;
if(succeed) then (yes)
  :update succeed count;
 else
 :retry multiple times;
 :update failed count;
endif

|Download process|
:**step3**;
:update the status of picture in db;
:remove the pictures as demand;
stop
@enduml