GET http://super666.cn:5801/pool
Accept: */*
Cache-Control: no-cache

###

### 从当前目录导入books.xml
GET http://super666.cn:5801/import
Accept: */*
Cache-Control: no-cache

###

### 从当前目录导入books.xml
GET http://super666.cn:5801/export
Accept: */*
Cache-Control: no-cache

###

GET http://super666.cn:5801/global
Accept: */*
Cache-Control: no-cache

<> 2020-03-12T024801.200.json

###

###

GET http://super666.cn:5801/book/delete/pic
Accept: */*
Cache-Control: no-cache

<> 2020-03-12T024801.200.json

###

###

GET http://super666.cn:5801/book/delete/all
Accept: */*
Cache-Control: no-cache

<> 2020-03-12T024801.200.json

###

### 确定手动创建一个global对象
### Send POST request with json body
POST http://super666.cn:5801/global
Content-Type: application/json

{
  "homeUrl": "http://www.177pic.pw/",
  "downloadThreadCount": 6,
  "storageDirectory": "/home/ubuntu/pic3",
  "numberOfRetries": 3,
  "downloadTimeout": 30000
}

### 确定手动创建一个global对象
### Send POST request with json body
POST http://super666.cn:5801/global
Content-Type: application/json

{
  "homeUrl": "https://www.wapmh.com/",
  "downloadThreadCount": 6,
  "storageDirectory": "/home/ubuntu/pic3",
  "numberOfRetries": 3,
  "downloadTimeout": 30000
}


### Send POST request with json body
GET http://super666.cn:5801/pool
Content-Type: application/json

###

GET http://super666.cn:5801/book/list/all
Accept: */*
Cache-Control: no-cache

<> 2020-03-12T024801.200.json

### download

GET http://super666.cn:5801/book/smart
Accept: */*
Cache-Control: no-cache

<> 2020-03-12T024801.200.json

###