
spring:
  datasource:
    url: "jdbc:h2:file:~/h2/download-pic;DB_CLOSE_ON_EXIT=FALSE"
    #    url: "jdbc:h2:mem:web;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE"
    username: root
    password: 1
    driver-class-name: org.h2.Driver
    platform: h2
    tomcat:
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 300000
      max-wait: 10000
      max-active: 50
      max-idle: 20
      min-idle: 5
      remove-abandoned: true
      remove-abandoned-timeout: 40
      num-tests-per-eviction-run: 0
      test-while-idle: false
      test-on-borrow: true # Validate the connection before borrowing it from the pool. to avoid SQL exception: Connection has already been closed
    continue-on-error: true # Do not stop if an error occurs while initializing the database
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
