login:
  username: root
  password: 1

spring:
  application:
    name: download-pic
  profiles:
    include: batch, h2, cache

# Set log level
logging:
  level:
    root: INFO

page:
  books: ".comic-list .thumbnail"
  subpage:
    count: ".chapter-list .item a"