spring:
  cache:
    # Enable ehcache (in-memory cache)
    ehcache:
      config: classpath:ehcache.xml
  aop:
    auto: true  # Add @EnableAspectJAutoProxy.
    proxy-target-class: true # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).
