spring:
  datasource:
    url: "jdbc:mysql://10.113.49.228:5808/slc?serverTimezone=GMT&autoReconnect=false&useSSL=false"
    username: test
    password: test
    driver-class-name:  com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update # Initialize the database by using JPA in
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        use-new-id-generator-mappings: AUTO   # add auto_increment for id
        show_sql: false
        use_sql_comments: false
        format_sql: false
    database: mysql